// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/komminarlabs/pulumi-cratedb/sdk/go/cratedb/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The API key
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "cratedb:apiKey")
}

// The API secret
func GetApiSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "cratedb:apiSecret")
}

// The CrateDB Cloud URL
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "cratedb:url")
}
