// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.CrateDB.Outputs
{

    [OutputType]
    public sealed class GetClusterHealthResult
    {
        /// <summary>
        /// The last seen time.
        /// </summary>
        public readonly string LastSeen;
        /// <summary>
        /// The type of the currently running operation. Returns an empty string if there is no operation in progress.
        /// </summary>
        public readonly string RunningOperation;
        /// <summary>
        /// The health status of the cluster.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetClusterHealthResult(
            string lastSeen,

            string runningOperation,

            string status)
        {
            LastSeen = lastSeen;
            RunningOperation = runningOperation;
            Status = status;
        }
    }
}
