// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.CrateDB.Outputs
{

    [OutputType]
    public sealed class GetClusterLastAsyncOperationResult
    {
        /// <summary>
        /// The DublinCore of the cluster.
        /// </summary>
        public readonly Outputs.GetClusterLastAsyncOperationDcResult Dc;
        /// <summary>
        /// The id of the last async operation.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The status of the last async operation.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The type of the last async operation.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetClusterLastAsyncOperationResult(
            Outputs.GetClusterLastAsyncOperationDcResult dc,

            string id,

            string status,

            string type)
        {
            Dc = dc;
            Id = id;
            Status = status;
            Type = type;
        }
    }
}
