// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.cratedb.Outputs
{

    [OutputType]
    public sealed class GetOrganizationsOrganizationResult
    {
        /// <summary>
        /// The DublinCore of the organization.
        /// </summary>
        public readonly Outputs.GetOrganizationsOrganizationDcResult Dc;
        /// <summary>
        /// The notification email used in the organization.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// The id of the organization.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the organization.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Whether notifications enabled for the organization.
        /// </summary>
        public readonly bool NotificationsEnabled;
        /// <summary>
        /// The support plan type used in the organization.
        /// </summary>
        public readonly double PlanType;
        /// <summary>
        /// The project count in the organization.
        /// </summary>
        public readonly double ProjectCount;
        /// <summary>
        /// The role FQN.
        /// </summary>
        public readonly string RoleFqn;

        [OutputConstructor]
        private GetOrganizationsOrganizationResult(
            Outputs.GetOrganizationsOrganizationDcResult dc,

            string email,

            string id,

            string name,

            bool notificationsEnabled,

            double planType,

            double projectCount,

            string roleFqn)
        {
            Dc = dc;
            Email = email;
            Id = id;
            Name = name;
            NotificationsEnabled = notificationsEnabled;
            PlanType = planType;
            ProjectCount = projectCount;
            RoleFqn = roleFqn;
        }
    }
}
