// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ClusterDc {
    /**
     * The created time.
     */
    created?: pulumi.Input<string>;
    /**
     * The modified time.
     */
    modified?: pulumi.Input<string>;
}

export interface ClusterHardwareSpecs {
    /**
     * The cpus per node.
     */
    cpusPerNode?: pulumi.Input<number>;
    /**
     * The disk size per node in bytes.
     */
    diskSizePerNodeBytes?: pulumi.Input<number>;
    /**
     * The disk type.
     */
    diskType?: pulumi.Input<string>;
    /**
     * The disks per node.
     */
    disksPerNode?: pulumi.Input<number>;
    /**
     * The heap size in bytes.
     */
    heapSizeBytes?: pulumi.Input<number>;
    /**
     * The memory per node in bytes.
     */
    memoryPerNodeBytes?: pulumi.Input<number>;
}

export interface ClusterHealth {
    /**
     * The health status of the cluster.
     */
    status?: pulumi.Input<string>;
}

export interface ClusterIpWhitelist {
    /**
     * The CIDR.
     */
    cidr?: pulumi.Input<string>;
    /**
     * The description.
     */
    description?: pulumi.Input<string>;
}

export interface OrganizationDc {
    /**
     * The created time.
     */
    created?: pulumi.Input<string>;
    /**
     * The modified time.
     */
    modified?: pulumi.Input<string>;
}

export interface ProjectDc {
    /**
     * The created time.
     */
    created?: pulumi.Input<string>;
    /**
     * The modified time.
     */
    modified?: pulumi.Input<string>;
}
