// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.cratedb.Inputs
{

    public sealed class ClusterHealthGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The health status of the cluster.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public ClusterHealthGetArgs()
        {
        }
        public static new ClusterHealthGetArgs Empty => new ClusterHealthGetArgs();
    }
}
