// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.cratedb.Inputs
{

    public sealed class ClusterIpWhitelistGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The CIDR.
        /// </summary>
        [Input("cidr")]
        public Input<string>? Cidr { get; set; }

        /// <summary>
        /// The description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        public ClusterIpWhitelistGetArgs()
        {
        }
        public static new ClusterIpWhitelistGetArgs Empty => new ClusterIpWhitelistGetArgs();
    }
}
