// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * To retrieve all organizations.
 */
export function getOrganizations(opts?: pulumi.InvokeOptions): Promise<GetOrganizationsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cratedb:index/getOrganizations:getOrganizations", {
    }, opts);
}

/**
 * A collection of values returned by getOrganizations.
 */
export interface GetOrganizationsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly organizations: outputs.GetOrganizationsOrganization[];
}
/**
 * To retrieve all organizations.
 */
export function getOrganizationsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOrganizationsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cratedb:index/getOrganizations:getOrganizations", {
    }, opts);
}
